# Generated by Django 5.0.4 on 2024-04-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='converted_audio',
            field=models.FileField(blank=True, null=True, upload_to='converted/'),
        ),
    ]
